### ISSUE TITLE
Create first draft version of the SQAaaS-web

### ISSUE THREAD

**Issue by gmolto** [EOSC-synergy/sqaaas-web#1]

**Comment by gmolto** [comment]
A tentative skeleton for the web is available at: [https://eosc-synergy.github.io/sqaaas-web](https://eosc-synergy.github.io/sqaaas-web), kindly created by @dianamariand92 

Suggestions for improvements are welcome.

Awaiting for the SQAaaS API to further continue development.

**Comment by orviz** [comment]
Depends on https://github.com/EOSC-synergy/SQAaaS/issues/1

**Comment by gmolto** [comment]
First draft version of the web (without SQAaaS API integration) is available in https://sqaaas.eosc-synergy.eu/. Kudos to @dianamariand92

**Comment by orviz** [comment]
If you agree this issue can be closed
