### ISSUE TITLE
Load dynamically the supported tools (per-criterion) from /criteria path

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#106]
SQAaaS will support a series of tools relevant to each criterion. The tools' descriptions can be obtained by using the `/criteria` path from the API.

The idea is that once the criterion is selected, the supported tools will appear in a dropdown so the user can select one or many. This means that the current requirement about **requiring at least one service definition will no longer be required**, since the definition of services associated with the tools will be automatically handled by the API.

**Comment by dianamariand92** [comment]
@orviz I have a first version ready on the web, to be able to modify the arguments of the tools from the web interface. I need to be able to test it directly with the API, to correct the problems that may arise. Would it be possible to modify the dev API?

**Comment by orviz** [comment]
nice @dianamariand92 !

Yes, sure the API dev should be modified to test your changes. As it is now, the API dev is pointing to the [prototype/1.1-no-polymorphism](https://github.com/EOSC-synergy/sqaaas-deploy/blob/main/deploy_sqaaas-api-dev.yaml#L18) branch, so any changes you might want to do shall be merged there. Let me know if you need help from my side

**Comment by dianamariand92** [comment]
Hi @orviz Right now all the tools return selectable in false (are hardcode). At some point, we saw an example in which this property was true and there could be several arguments. This is what I need to test the code on the web.

**Comment by orviz** [comment]
@dianamariand92 there is a new PR https://github.com/EOSC-synergy/sqa-composer-templates/pull/25 that adds an optional argument to the `hadolint` tool. As far as I can see, this should be enough for testing what you want. If so, please approve the change.

**Comment by dianamariand92** [comment]
Hi @orviz I already approved the changes. This is useful but if we can have a tool with multiple args nested it would be better because I also want to test the recursive function that I implemented on the web.

**Comment by orviz** [comment]
@dianamariand92 I see that others are testing tools committing to the same branch (like the FAIR tools), so I would rather perform these tests incrementally to avoid outages when using the staging environment.

Once you have this one tested, we could try the recursive. For this, copy one of the examples with recursive args from the `main` branch and create a PR to `feature/dynamic_tool_gathering`. If not me, other reviewers can approve it.

**Comment by orviz** [comment]
Released in SQAaaS platform 1.1.1
