### ISSUE TITLE
The '+ add tool' button does not appear for certain tools

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#122]
# Steps to reproduce:
1. Log into the production portal & skip both the repo and service definition
2. When the criteria is loaded, click on e.g. `Qc.Lic` and then on `jsonlint`

the '+add tool' button does not appear and consequently the criterion cannot be added.

Seems to be only happening with tools that do not have arguments. Indeed, after selecting one of the tools with args, the issue is not reproducible anymore, unless you go back and forth to the previous view (so the criteria is reloaded)

**Comment by dianamariand92** [comment]
Solved. In production.
