### ISSUE TITLE
Spinner window keeps loading forever

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#144]
In the inputs view of the QAA module the spinner window is not closed when the API returns 500.
The web needs to present a generic error message and close the spinner.

![image](https://user-images.githubusercontent.com/1225231/158161819-c104eca7-94e9-43c7-98b6-97ae3f907fa4.png)

**Comment by dianamariand92** [comment]
@orviz This is done in staging and in production.

**Comment by orviz** [comment]
This issue is still there: the API returns 500, the web then shows a popup (containing just "Error" message) for a few seconds, and the spinner keeps running forever 

![image](https://user-images.githubusercontent.com/1225231/167635462-e209b3cb-7ecf-4338-8c79-0f49114834a9.png)
