### ISSUE TITLE
Contextualize step 2 (Services) towards Tooling

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#147]
The title of current step 2 (Services) can be misleading as it seems like the place where one has to define the (micro)services needed for the service deployment. Indeed this task will be done in step 3 (Criteria).

Instead, the services in step 2 are the ones required for assessing their quality, so it seems like a better approach to rename it as *Tooling*, and similarly, be more precise in the description text from the header.

**Comment by dianamariand92** [comment]
@orviz I have changed the title in the side menu, we still have to change the information once the user is in that step.

**Comment by orviz** [comment]
@dianamariand92 just updated the description for step 2
