### ISSUE TITLE
Cosmetic changes in 1.2.0-alpha

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#158]
To improve:

- [x] Change the ID of the criterion, in each table's header, to use the same the same [approach as in the baseline](https://indigo-dc.github.io/sqa-baseline/#code-accessibility-qc.acc). For instance **Code accessibility (QC.Acc)* instead of just *QC.Acc*
- [x] Reduce padding both in all the rows (both header and subcriteria rows)
- [x] Reduce indentation in the evidence messages (currently it seems too far to the right)
- [x] Fix newline when the evidence message is too long (currently the message is placed under the success/fail icon)
- [x] Increase the font of subcriteria description and evidence??

**Comment by dianamariand92** [comment]
@orviz All these improvements are in the stage-api branch. Please check it.

**Comment by orviz** [comment]
@dianamariand92 perfect thanks!

**Comment by orviz** [comment]
Released under `1.2.0-alpha1`
