### ISSUE TITLE
Add a help icon to each input field

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#39]
A help icon (question mark) could be added for each input field as a way to guide the user in the values expected. A brief and concise help message should be displayed either by clicking on the icon or by hovering over it

**Comment by dianamariand92** [comment]
I have included an example help icon in the General Options form (Customize Workspace). We have to define the message to show and in which inputs it will be shown since, for example in the Repository Name or Repository URL, I think it is not necessary.

**Comment by dianamariand92** [comment]
Working on defining the input and the message.

**Comment by dianamariand92** [comment]
Added on staging.

**Comment by orviz** [comment]
Released in SQAaaS platform 1.1.1
