### ISSUE TITLE
Implement the docker push feature from JePL 2.1.0

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#40]
JePL 2.1.0 allows the user to [push the resultant images to a Docker registry (of her/his choice)](https://indigo-dc.github.io/jenkins-pipeline-library/release/2.1.0/user/config_file.html#docker-registry-upload-images). The web forms should provide a means to do that.

**Comment by orviz** [comment]
@samuelbernardolip

**Comment by dianamariand92** [comment]
Solved
