### ISSUE TITLE
Separate config.yml and docker-compose.yml in separate views (parent: general options)

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#44]
Currently, both the config.yml and docker-compose.yml files are defined in the same view. For the sake of clearness, we should separate them into individual views, so that they appear as substeps of the "General Options" step.

**Comment by orviz** [comment]
This could be even changed to:
- "config.yml" -> "General options"
- "docker-compose.yml" -> "Composer options"

since we are thinking in supporting new composers, such as plain docker. Any ideas here @samuelbernardolip ?

**Comment by dianamariand92** [comment]
Solved in the new version of the web.
