### ISSUE TITLE
Allow to compose pipelines that fetch the code version that activated the build

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#57]
JePL allows to fetch the code version that triggered the build (instead of a fixed version defined in `config:project_repos`) and use that for the validation of the given criterion. This is done by removing the `repos` property within `sqa_criteria:<criterion>`, and currently [supported by the jpl-validator](https://github.com/EOSC-synergy/jpl-validator/pull/34).

Unfortunately, this feature is not yet documented in JePL, there is an issue for that: https://github.com/indigo-dc/jenkins-pipeline-library/issues/142

**Comment by orviz** [comment]
In staging: https://github.com/EOSC-synergy/sqaaas-api-server/issues/32

**Comment by orviz** [comment]
There is an additional feature that can be added in the web and performed by the API. In the event of having such type of non-repo definitions for a given criterion (basically what this issue is dealing), it is known that the "Run pipeline" feature will not have the code in the (*.sqaaas) repository, and thus the pipeline execution will not succeed.

One solution for this is that whenever the "Run pipeline" is requested by the user, the web warns about this fact and provides the possibility to fetch the code from the upstream repository the pipeline is meant to be added. This will mimic the future execution of the pipeline in the appropriate environment.

**Comment by dianamariand92** [comment]
Pushed changes to the master branch (production web).
