### ISSUE TITLE
Embed HTML code for badges in the result page

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#58]
The API server now [supports creating badges](https://eosc-synergy.github.io/sqaaas-api-spec/#operation/issue_badge), by means of the Badgr API, which are available in the [test profile in eu.badgr.io](https://eu.badgr.com/issuers/606d4fa3eb549373b7a1aefa/badges/606d5893eb549373b7a1b0b4/assertions). The result of this request returns data that is required for composing the HTML code that shall be embedded in the web.

The HTML code and required data is documented in the following issue:

https://github.com/EOSC-synergy/sqaaas-api-server/issues/23

**Comment by dianamariand92** [comment]
Pushed changes to the master branch (production web).
